language: java
jdk:
  - openjdk11

services:
  - docker

addons:
  sonarcloud:
    organization: "adilsonsilva-github"
    token: $SONAR_TOKEN # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

#env:
# global:
#    secure: IMAGE_NAME
#    secure: HEROKU_API_KEY
#    secure: DOCKER_USER
#    secure: DOCKER_PASS

before_install:
  - docker pull openjdk:11-jdk-slim
# Test & Build SpringBoot app
script:
  - mvn test
  - mvn clean package
# Create Docker image for our app and push it to Dockerhub repository and send messages to the Teams channel after the `script` job is successfully executed
after_success:
  - export COMMIT=${TRAVIS_COMMIT::7}
  - export TAG=`if [ ! -z "$TRAVIS_TAG" ]; then echo "$TRAVIS_TAG"; else echo "$TRAVIS_BRANCH--$COMMIT"; fi`
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker-compose build
  - docker tag adilsonsilva86/api-account-launch:latest adilsonsilva86/api-account-launch:$TAG
  - docker push adilsonsilva86/api-account-launch:$TAG
  - export TITLE="adilsonsilva86/api-account-launch:$TAG is built properly and pushed to Dockerhub"
  - export TIMESTAMP=`date`
  - export GIT_LOG=`git log -1 --pretty=%B $COMMIT`
  - export TEXT="[build version] $TAG<br />[datetime] $TIMESTAMP<br />[changelog] $GIT_LOG<br />"
#  - chmod +x send_to_teams.sh && ./send_to_teams.sh
# If the `script` job fails, it will send a failure message to Teams channel
after_failure:
  - export TITLE="Travis:$TRAVIS_JOB_ID -- build job is failed"
  - export TEXT=[datetime]:`date`

branches:
    only:
    - master
    - /v\d+\.\d+[a-z]/

# Allow Travis to help deploy the app on Heroku
deploy:
  provider: heroku
  api-key:
    secure: "$HEROKU_API_KEY"

# Send the message of success after the deploy is done properly
after_deploy:
  - export TITLE="🎉🎉🎉New version $TAG is deployed to Heroku production🎉🎉🎉"
  - export TEXT=[datetime]:`date`
